// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"time"
)

type AddEnvironmentVariableToContextRequestBody struct {
	// The value of the environment variable
	Value string `json:"value"`
}

type AddEnvironmentVariableToContextRequest struct {
	RequestBody *AddEnvironmentVariableToContextRequestBody `request:"mediaType=application/json"`
	// ID of the context (UUID)
	ContextID string `pathParam:"style=simple,explode=false,name=context-id"`
	// The name of the environment variable
	EnvVarName string `pathParam:"style=simple,explode=false,name=env-var-name"`
}

// AddEnvironmentVariableToContextDefaultApplicationJSON - Error response.
type AddEnvironmentVariableToContextDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// AddEnvironmentVariableToContext200ApplicationJSONMessageResponse - message response
type AddEnvironmentVariableToContext200ApplicationJSONMessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}

type AddEnvironmentVariableToContext200ApplicationJSON1 struct {
	// ID of the context (UUID)
	ContextID string `json:"context_id"`
	// The date and time the environment variable was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the environment variable was updated
	UpdatedAt time.Time `json:"updated_at"`
	// The name of the environment variable
	Variable string `json:"variable"`
}

type AddEnvironmentVariableToContextResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The new environment variable
	AddEnvironmentVariableToContext200ApplicationJSONAnyOf interface{}
	// Error response.
	AddEnvironmentVariableToContextDefaultApplicationJSONObject *AddEnvironmentVariableToContextDefaultApplicationJSON
}
