// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CancelWorkflowRequest struct {
	// The unique ID of the workflow.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

// CancelWorkflowDefaultApplicationJSON - Error response.
type CancelWorkflowDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CancelWorkflowMessageResponse - message response
type CancelWorkflowMessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}

type CancelWorkflowResponse struct {
	ContentType string
	// A confirmation message.
	MessageResponse *CancelWorkflowMessageResponse
	StatusCode      int
	RawResponse     *http.Response
	// Error response.
	CancelWorkflowDefaultApplicationJSONObject *CancelWorkflowDefaultApplicationJSON
}
