// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

// CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType - The type of checkout key to create. This may be either `deploy-key` or `user-key`.
type CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType string

const (
	CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeUserKey   CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType = "user-key"
	CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeDeployKey CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType = "deploy-key"
)

func (e CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType) ToPointer() *CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType {
	return &e
}

func (e *CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user-key":
		fallthrough
	case "deploy-key":
		*e = CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType: %v", v)
	}
}

type CreateCheckoutKeyCheckoutKeyInput struct {
	// The type of checkout key to create. This may be either `deploy-key` or `user-key`.
	Type CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputType `json:"type"`
}

type CreateCheckoutKeyRequest struct {
	RequestBody *CreateCheckoutKeyCheckoutKeyInput `request:"mediaType=application/json"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// CreateCheckoutKeyDefaultApplicationJSON - Error response.
type CreateCheckoutKeyDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateCheckoutKeyCheckoutKeyCheckoutKeyType - The type of checkout key. This may be either `deploy-key` or `github-user-key`.
type CreateCheckoutKeyCheckoutKeyCheckoutKeyType string

const (
	CreateCheckoutKeyCheckoutKeyCheckoutKeyTypeDeployKey     CreateCheckoutKeyCheckoutKeyCheckoutKeyType = "deploy-key"
	CreateCheckoutKeyCheckoutKeyCheckoutKeyTypeGithubUserKey CreateCheckoutKeyCheckoutKeyCheckoutKeyType = "github-user-key"
)

func (e CreateCheckoutKeyCheckoutKeyCheckoutKeyType) ToPointer() *CreateCheckoutKeyCheckoutKeyCheckoutKeyType {
	return &e
}

func (e *CreateCheckoutKeyCheckoutKeyCheckoutKeyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deploy-key":
		fallthrough
	case "github-user-key":
		*e = CreateCheckoutKeyCheckoutKeyCheckoutKeyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCheckoutKeyCheckoutKeyCheckoutKeyType: %v", v)
	}
}

// CreateCheckoutKeyCheckoutKey - The checkout key.
type CreateCheckoutKeyCheckoutKey struct {
	// The date and time the checkout key was created.
	CreatedAt time.Time `json:"created-at"`
	// An SSH key fingerprint.
	Fingerprint string `json:"fingerprint"`
	// A boolean value that indicates if this key is preferred.
	Preferred bool `json:"preferred"`
	// A public SSH key.
	PublicKey string `json:"public-key"`
	// The type of checkout key. This may be either `deploy-key` or `github-user-key`.
	Type CreateCheckoutKeyCheckoutKeyCheckoutKeyType `json:"type"`
}

type CreateCheckoutKeyResponse struct {
	// The checkout key.
	CheckoutKey *CreateCheckoutKeyCheckoutKey
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Error response.
	CreateCheckoutKeyDefaultApplicationJSONObject *CreateCheckoutKeyDefaultApplicationJSON
}
