// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type CreateWebhookRequestBodyEvents string

const (
	CreateWebhookRequestBodyEventsWorkflowCompleted CreateWebhookRequestBodyEvents = "workflow-completed"
	CreateWebhookRequestBodyEventsJobCompleted      CreateWebhookRequestBodyEvents = "job-completed"
)

func (e CreateWebhookRequestBodyEvents) ToPointer() *CreateWebhookRequestBodyEvents {
	return &e
}

func (e *CreateWebhookRequestBodyEvents) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "workflow-completed":
		fallthrough
	case "job-completed":
		*e = CreateWebhookRequestBodyEvents(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateWebhookRequestBodyEvents: %v", v)
	}
}

// CreateWebhookRequestBodyScopeType - Type of the scope being used
type CreateWebhookRequestBodyScopeType string

const (
	CreateWebhookRequestBodyScopeTypeProject CreateWebhookRequestBodyScopeType = "project"
)

func (e CreateWebhookRequestBodyScopeType) ToPointer() *CreateWebhookRequestBodyScopeType {
	return &e
}

func (e *CreateWebhookRequestBodyScopeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "project":
		*e = CreateWebhookRequestBodyScopeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateWebhookRequestBodyScopeType: %v", v)
	}
}

// CreateWebhookRequestBodyScope - The scope in which the relevant events that will trigger webhooks
type CreateWebhookRequestBodyScope struct {
	// ID of the scope being used (at the moment, only project ID is supported)
	ID string `json:"id"`
	// Type of the scope being used
	Type CreateWebhookRequestBodyScopeType `json:"type"`
}

// CreateWebhookRequestBody - The parameters for a create webhook request
type CreateWebhookRequestBody struct {
	// Events that will trigger the webhook
	Events []CreateWebhookRequestBodyEvents `json:"events"`
	// Name of the webhook
	Name string `json:"name"`
	// The scope in which the relevant events that will trigger webhooks
	Scope CreateWebhookRequestBodyScope `json:"scope"`
	// Secret used to build an HMAC hash of the payload and passed as a header in the webhook request
	SigningSecret string `json:"signing-secret"`
	// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
	URL string `json:"url"`
	// Whether to enforce TLS certificate verification when delivering the webhook
	VerifyTLS bool `json:"verify-tls"`
}

// CreateWebhookDefaultApplicationJSON - Error response.
type CreateWebhookDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type CreateWebhookWebhookEvents string

const (
	CreateWebhookWebhookEventsWorkflowCompleted CreateWebhookWebhookEvents = "workflow-completed"
	CreateWebhookWebhookEventsJobCompleted      CreateWebhookWebhookEvents = "job-completed"
)

func (e CreateWebhookWebhookEvents) ToPointer() *CreateWebhookWebhookEvents {
	return &e
}

func (e *CreateWebhookWebhookEvents) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "workflow-completed":
		fallthrough
	case "job-completed":
		*e = CreateWebhookWebhookEvents(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateWebhookWebhookEvents: %v", v)
	}
}

// CreateWebhookWebhookScope - The scope in which the relevant events that will trigger webhooks
type CreateWebhookWebhookScope struct {
	// ID of the scope being used (at the moment, only project ID is supported)
	ID string `json:"id"`
	// Type of the scope being used
	Type string `json:"type"`
}

// CreateWebhookWebhook - A webhook
type CreateWebhookWebhook struct {
	// The date and time the webhook was created.
	CreatedAt time.Time `json:"created-at"`
	// Events that will trigger the webhook
	Events []CreateWebhookWebhookEvents `json:"events"`
	// The unique ID of the webhook
	ID string `json:"id"`
	// Name of the webhook
	Name string `json:"name"`
	// The scope in which the relevant events that will trigger webhooks
	Scope CreateWebhookWebhookScope `json:"scope"`
	// Masked value of the secret used to build an HMAC hash of the payload and passed as a header in the webhook request
	SigningSecret string `json:"signing-secret"`
	// The date and time the webhook was last updated.
	UpdatedAt time.Time `json:"updated-at"`
	// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
	URL string `json:"url"`
	// Whether to enforce TLS certificate verification when delivering the webhook
	VerifyTLS bool `json:"verify-tls"`
}

type CreateWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A webhook
	Webhook *CreateWebhookWebhook
	// Error response.
	CreateWebhookDefaultApplicationJSONObject *CreateWebhookDefaultApplicationJSON
}
