// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// CreateEnvVarEnvironmentVariablePair - The environment variable.
type CreateEnvVarEnvironmentVariablePair struct {
	// The name of the environment variable.
	Name string `json:"name"`
	// The value of the environment variable.
	Value string `json:"value"`
}

type CreateEnvVarRequest struct {
	RequestBody *CreateEnvVarEnvironmentVariablePair `request:"mediaType=application/json"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// CreateEnvVarDefaultApplicationJSON - Error response.
type CreateEnvVarDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type CreateEnvVarResponse struct {
	ContentType string
	// The environment variable.
	EnvironmentVariablePair *CreateEnvVarEnvironmentVariablePair
	StatusCode              int
	RawResponse             *http.Response
	// Error response.
	CreateEnvVarDefaultApplicationJSONObject *CreateEnvVarDefaultApplicationJSON
}
