// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteContextRequest struct {
	// ID of the context (UUID)
	ContextID string `pathParam:"style=simple,explode=false,name=context-id"`
}

// DeleteContextDefaultApplicationJSON - Error response.
type DeleteContextDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteContextMessageResponse - message response
type DeleteContextMessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}

type DeleteContextResponse struct {
	ContentType string
	// A confirmation message
	MessageResponse *DeleteContextMessageResponse
	StatusCode      int
	RawResponse     *http.Response
	// Error response.
	DeleteContextDefaultApplicationJSONObject *DeleteContextDefaultApplicationJSON
}
