// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteCheckoutKeyRequest struct {
	// An SSH key fingerprint.
	Fingerprint string `pathParam:"style=simple,explode=false,name=fingerprint"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// DeleteCheckoutKeyDefaultApplicationJSON - Error response.
type DeleteCheckoutKeyDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteCheckoutKeyMessageResponse - message response
type DeleteCheckoutKeyMessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}

type DeleteCheckoutKeyResponse struct {
	ContentType string
	// A confirmation message.
	MessageResponse *DeleteCheckoutKeyMessageResponse
	StatusCode      int
	RawResponse     *http.Response
	// Error response.
	DeleteCheckoutKeyDefaultApplicationJSONObject *DeleteCheckoutKeyDefaultApplicationJSON
}
