// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteEnvVarRequest struct {
	// The name of the environment variable.
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// DeleteEnvVarDefaultApplicationJSON - Error response.
type DeleteEnvVarDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteEnvVarMessageResponse - message response
type DeleteEnvVarMessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}

type DeleteEnvVarResponse struct {
	ContentType string
	// A confirmation message.
	MessageResponse *DeleteEnvVarMessageResponse
	StatusCode      int
	RawResponse     *http.Response
	// Error response.
	DeleteEnvVarDefaultApplicationJSONObject *DeleteEnvVarDefaultApplicationJSON
}
