// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteScheduleByIDRequest struct {
	// The unique ID of the schedule.
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule-id"`
}

// DeleteScheduleByIDDefaultApplicationJSON - Error response.
type DeleteScheduleByIDDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteScheduleByIDMessageResponse - message response
type DeleteScheduleByIDMessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}

type DeleteScheduleByIDResponse struct {
	ContentType string
	// A confirmation message.
	MessageResponse *DeleteScheduleByIDMessageResponse
	StatusCode      int
	RawResponse     *http.Response
	// Error response.
	DeleteScheduleByIDDefaultApplicationJSONObject *DeleteScheduleByIDDefaultApplicationJSON
}
