// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"time"
)

type GetContextRequest struct {
	// ID of the context (UUID)
	ContextID string `pathParam:"style=simple,explode=false,name=context-id"`
}

// GetContextDefaultApplicationJSON - Error response.
type GetContextDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetContextContext - The context
type GetContextContext struct {
	// The date and time the context was created.
	CreatedAt time.Time `json:"created_at"`
	// The unique ID of the context.
	ID string `json:"id"`
	// The user defined name of the context.
	Name string `json:"name"`
}

type GetContextResponse struct {
	ContentType string
	// The context
	Context     *GetContextContext
	StatusCode  int
	RawResponse *http.Response
	// Error response.
	GetContextDefaultApplicationJSONObject *GetContextDefaultApplicationJSON
}
