// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type GetCheckoutKeyRequest struct {
	// An SSH key fingerprint.
	Fingerprint string `pathParam:"style=simple,explode=false,name=fingerprint"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// GetCheckoutKeyDefaultApplicationJSON - Error response.
type GetCheckoutKeyDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum - The type of checkout key. This may be either `deploy-key` or `github-user-key`.
type GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum string

const (
	GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnumDeployKey     GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum = "deploy-key"
	GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnumGithubUserKey GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum = "github-user-key"
)

func (e GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum) ToPointer() *GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum {
	return &e
}

func (e *GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deploy-key":
		fallthrough
	case "github-user-key":
		*e = GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum: %v", v)
	}
}

// GetCheckoutKeyCheckoutKey - The checkout key.
type GetCheckoutKeyCheckoutKey struct {
	// The date and time the checkout key was created.
	CreatedAt time.Time `json:"created-at"`
	// An SSH key fingerprint.
	Fingerprint string `json:"fingerprint"`
	// A boolean value that indicates if this key is preferred.
	Preferred bool `json:"preferred"`
	// A public SSH key.
	PublicKey string `json:"public-key"`
	// The type of checkout key. This may be either `deploy-key` or `github-user-key`.
	Type GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum `json:"type"`
}

type GetCheckoutKeyResponse struct {
	// The checkout key.
	CheckoutKey *GetCheckoutKeyCheckoutKey
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Error response.
	GetCheckoutKeyDefaultApplicationJSONObject *GetCheckoutKeyDefaultApplicationJSON
}
