// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// GetCurrentUserDefaultApplicationJSON - Error response.
type GetCurrentUserDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetCurrentUserUser - User login information.
type GetCurrentUserUser struct {
	// The unique ID of the user.
	ID string `json:"id"`
	// The login information for the user on the VCS.
	Login string `json:"login"`
	// The name of the user.
	Name string `json:"name"`
}

type GetCurrentUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// User login information.
	User *GetCurrentUserUser
	// Error response.
	GetCurrentUserDefaultApplicationJSONObject *GetCurrentUserDefaultApplicationJSON
}
