// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetEnvVarRequest struct {
	// The name of the environment variable.
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// GetEnvVarDefaultApplicationJSON - Error response.
type GetEnvVarDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetEnvVarEnvironmentVariablePair - The environment variable.
type GetEnvVarEnvironmentVariablePair struct {
	// The name of the environment variable.
	Name string `json:"name"`
	// The value of the environment variable.
	Value string `json:"value"`
}

type GetEnvVarResponse struct {
	ContentType string
	// The environment variable.
	EnvironmentVariablePair *GetEnvVarEnvironmentVariablePair
	StatusCode              int
	RawResponse             *http.Response
	// Error response.
	GetEnvVarDefaultApplicationJSONObject *GetEnvVarDefaultApplicationJSON
}
