// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetJobArtifactsRequest struct {
	// The number of the job.
	JobNumber interface{} `pathParam:"style=simple,explode=false,name=job-number"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// GetJobArtifactsDefaultApplicationJSON - Error response.
type GetJobArtifactsDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetJobArtifactsArtifactListResponseArtifact - An artifact
type GetJobArtifactsArtifactListResponseArtifact struct {
	// The index of the node that stored the artifact.
	NodeIndex int64 `json:"node_index"`
	// The artifact path.
	Path string `json:"path"`
	// The URL to download the artifact contents.
	URL string `json:"url"`
}

// GetJobArtifactsArtifactListResponse - A paginated list of the job's artifacts.
type GetJobArtifactsArtifactListResponse struct {
	Items []GetJobArtifactsArtifactListResponseArtifact `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

type GetJobArtifactsResponse struct {
	// A paginated list of the job's artifacts.
	ArtifactListResponse *GetJobArtifactsArtifactListResponse
	ContentType          string
	StatusCode           int
	RawResponse          *http.Response
	// Error response.
	GetJobArtifactsDefaultApplicationJSONObject *GetJobArtifactsDefaultApplicationJSON
}
