// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetPipelineConfigByIDRequest struct {
	// The unique ID of the pipeline.
	PipelineID string `pathParam:"style=simple,explode=false,name=pipeline-id"`
}

// GetPipelineConfigByIDDefaultApplicationJSON - Error response.
type GetPipelineConfigByIDDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetPipelineConfigByIDPipelineConfig - The configuration strings for the pipeline.
type GetPipelineConfigByIDPipelineConfig struct {
	// The compiled configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's configuration, then this field may be empty.
	Compiled string `json:"compiled"`
	// The compiled setup configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's setup workflows, then this field may be empty.
	CompiledSetupConfig *string `json:"compiled-setup-config,omitempty"`
	// The setup configuration for the pipeline used for Setup Workflows. If there were errors processing the pipeline's configuration or if setup workflows are not enabled, then this field should not exist
	SetupConfig *string `json:"setup-config,omitempty"`
	// The source configuration for the pipeline, before any config compilation has been performed. If there is no config, then this field will be empty.
	Source string `json:"source"`
}

type GetPipelineConfigByIDResponse struct {
	ContentType string
	// The configuration strings for the pipeline.
	PipelineConfig *GetPipelineConfigByIDPipelineConfig
	StatusCode     int
	RawResponse    *http.Response
	// Error response.
	GetPipelineConfigByIDDefaultApplicationJSONObject *GetPipelineConfigByIDDefaultApplicationJSON
}
