// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type GetPipelineByIDRequest struct {
	// The unique ID of the pipeline.
	PipelineID string `pathParam:"style=simple,explode=false,name=pipeline-id"`
}

// GetPipelineByIDDefaultApplicationJSON - Error response.
type GetPipelineByIDDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetPipelineByIDPipelineErrorsType - The type of error.
type GetPipelineByIDPipelineErrorsType string

const (
	GetPipelineByIDPipelineErrorsTypeConfig      GetPipelineByIDPipelineErrorsType = "config"
	GetPipelineByIDPipelineErrorsTypeConfigFetch GetPipelineByIDPipelineErrorsType = "config-fetch"
	GetPipelineByIDPipelineErrorsTypeTimeout     GetPipelineByIDPipelineErrorsType = "timeout"
	GetPipelineByIDPipelineErrorsTypePermission  GetPipelineByIDPipelineErrorsType = "permission"
	GetPipelineByIDPipelineErrorsTypeOther       GetPipelineByIDPipelineErrorsType = "other"
	GetPipelineByIDPipelineErrorsTypePlan        GetPipelineByIDPipelineErrorsType = "plan"
)

func (e GetPipelineByIDPipelineErrorsType) ToPointer() *GetPipelineByIDPipelineErrorsType {
	return &e
}

func (e *GetPipelineByIDPipelineErrorsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "config":
		fallthrough
	case "config-fetch":
		fallthrough
	case "timeout":
		fallthrough
	case "permission":
		fallthrough
	case "other":
		fallthrough
	case "plan":
		*e = GetPipelineByIDPipelineErrorsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetPipelineByIDPipelineErrorsType: %v", v)
	}
}

// GetPipelineByIDPipelineErrors - An error with a type and message.
type GetPipelineByIDPipelineErrors struct {
	// A human-readable error message.
	Message string `json:"message"`
	// The type of error.
	Type GetPipelineByIDPipelineErrorsType `json:"type"`
}

// GetPipelineByIDPipelineState - The current state of the pipeline.
type GetPipelineByIDPipelineState string

const (
	GetPipelineByIDPipelineStateCreated      GetPipelineByIDPipelineState = "created"
	GetPipelineByIDPipelineStateErrored      GetPipelineByIDPipelineState = "errored"
	GetPipelineByIDPipelineStateSetupPending GetPipelineByIDPipelineState = "setup-pending"
	GetPipelineByIDPipelineStateSetup        GetPipelineByIDPipelineState = "setup"
	GetPipelineByIDPipelineStatePending      GetPipelineByIDPipelineState = "pending"
)

func (e GetPipelineByIDPipelineState) ToPointer() *GetPipelineByIDPipelineState {
	return &e
}

func (e *GetPipelineByIDPipelineState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created":
		fallthrough
	case "errored":
		fallthrough
	case "setup-pending":
		fallthrough
	case "setup":
		fallthrough
	case "pending":
		*e = GetPipelineByIDPipelineState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetPipelineByIDPipelineState: %v", v)
	}
}

// GetPipelineByIDPipelineTriggerActor - The user who triggered the Pipeline.
type GetPipelineByIDPipelineTriggerActor struct {
	// URL to the user's avatar on the VCS
	AvatarURL string `json:"avatar_url"`
	// The login information for the user on the VCS.
	Login string `json:"login"`
}

// GetPipelineByIDPipelineTriggerType - The type of trigger.
type GetPipelineByIDPipelineTriggerType string

const (
	GetPipelineByIDPipelineTriggerTypeScheduledPipeline GetPipelineByIDPipelineTriggerType = "scheduled_pipeline"
	GetPipelineByIDPipelineTriggerTypeExplicit          GetPipelineByIDPipelineTriggerType = "explicit"
	GetPipelineByIDPipelineTriggerTypeAPI               GetPipelineByIDPipelineTriggerType = "api"
	GetPipelineByIDPipelineTriggerTypeWebhook           GetPipelineByIDPipelineTriggerType = "webhook"
)

func (e GetPipelineByIDPipelineTriggerType) ToPointer() *GetPipelineByIDPipelineTriggerType {
	return &e
}

func (e *GetPipelineByIDPipelineTriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "scheduled_pipeline":
		fallthrough
	case "explicit":
		fallthrough
	case "api":
		fallthrough
	case "webhook":
		*e = GetPipelineByIDPipelineTriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetPipelineByIDPipelineTriggerType: %v", v)
	}
}

// GetPipelineByIDPipelineTrigger - A summary of the trigger.
type GetPipelineByIDPipelineTrigger struct {
	// The user who triggered the Pipeline.
	Actor GetPipelineByIDPipelineTriggerActor `json:"actor"`
	// The date and time the trigger was received.
	ReceivedAt time.Time `json:"received_at"`
	// The type of trigger.
	Type GetPipelineByIDPipelineTriggerType `json:"type"`
}

// GetPipelineByIDPipelineVcsCommit - The latest commit in the pipeline.
type GetPipelineByIDPipelineVcsCommit struct {
	// The body of the commit message.
	Body string `json:"body"`
	// The subject of the commit message.
	Subject string `json:"subject"`
}

// GetPipelineByIDPipelineVcs - VCS information for the pipeline.
type GetPipelineByIDPipelineVcs struct {
	// The branch where the pipeline ran. The HEAD commit on this branch was used for the pipeline. Note that `branch` and `tag` are mutually exclusive. To trigger a pipeline for a PR by number use `pull/<number>/head` for the PR ref or `pull/<number>/merge` for the merge ref (GitHub only).
	Branch *string `json:"branch,omitempty"`
	// The latest commit in the pipeline.
	Commit *GetPipelineByIDPipelineVcsCommit `json:"commit,omitempty"`
	// URL for the repository where the trigger originated. For fork-PR pipelines, this is the URL to the fork. For other pipelines the `origin_` and `target_repository_url`s will be the same.
	OriginRepositoryURL string `json:"origin_repository_url"`
	// Name of the VCS provider (e.g. GitHub, Bitbucket).
	ProviderName string `json:"provider_name"`
	// The code review id.
	ReviewID *string `json:"review_id,omitempty"`
	// The code review URL.
	ReviewURL *string `json:"review_url,omitempty"`
	// The code revision the pipeline ran.
	Revision string `json:"revision"`
	// The tag used by the pipeline. The commit that this tag points to was used for the pipeline. Note that `branch` and `tag` are mutually exclusive.
	Tag *string `json:"tag,omitempty"`
	// URL for the repository the trigger targets (i.e. the repository where the PR will be merged). For fork-PR pipelines, this is the URL to the parent repo. For other pipelines, the `origin_` and `target_repository_url`s will be the same.
	TargetRepositoryURL string `json:"target_repository_url"`
}

// GetPipelineByIDPipeline - A pipeline response.
type GetPipelineByIDPipeline struct {
	// The date and time the pipeline was created.
	CreatedAt time.Time `json:"created_at"`
	// A sequence of errors that have occurred within the pipeline.
	Errors []GetPipelineByIDPipelineErrors `json:"errors"`
	// The unique ID of the pipeline.
	ID string `json:"id"`
	// The number of the pipeline.
	Number int64 `json:"number"`
	// The project-slug for the pipeline.
	ProjectSlug string `json:"project_slug"`
	// The current state of the pipeline.
	State GetPipelineByIDPipelineState `json:"state"`
	// A summary of the trigger.
	Trigger           GetPipelineByIDPipelineTrigger `json:"trigger"`
	TriggerParameters map[string]interface{}         `json:"trigger_parameters,omitempty"`
	// The date and time the pipeline was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// VCS information for the pipeline.
	Vcs *GetPipelineByIDPipelineVcs `json:"vcs,omitempty"`
}

type GetPipelineByIDResponse struct {
	ContentType string
	// A pipeline object.
	Pipeline    *GetPipelineByIDPipeline
	StatusCode  int
	RawResponse *http.Response
	// Error response.
	GetPipelineByIDDefaultApplicationJSONObject *GetPipelineByIDDefaultApplicationJSON
}
