// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type GetScheduleByIDRequest struct {
	// The unique ID of the schedule.
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule-id"`
}

// GetScheduleByIDDefaultApplicationJSON - Error response.
type GetScheduleByIDDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetScheduleByIDScheduleUser - The attribution actor who will run the scheduled pipeline.
type GetScheduleByIDScheduleUser struct {
	// The unique ID of the user.
	ID string `json:"id"`
	// The login information for the user on the VCS.
	Login string `json:"login"`
	// The name of the user.
	Name string `json:"name"`
}

// GetScheduleByIDScheduleTimetable2DaysOfWeekEnum - Day in a week, in three letters format
type GetScheduleByIDScheduleTimetable2DaysOfWeekEnum string

const (
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumTue GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "TUE"
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumSat GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "SAT"
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumSun GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "SUN"
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumMon GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "MON"
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumThu GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "THU"
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumWed GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "WED"
	GetScheduleByIDScheduleTimetable2DaysOfWeekEnumFri GetScheduleByIDScheduleTimetable2DaysOfWeekEnum = "FRI"
)

func (e GetScheduleByIDScheduleTimetable2DaysOfWeekEnum) ToPointer() *GetScheduleByIDScheduleTimetable2DaysOfWeekEnum {
	return &e
}

func (e *GetScheduleByIDScheduleTimetable2DaysOfWeekEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TUE":
		fallthrough
	case "SAT":
		fallthrough
	case "SUN":
		fallthrough
	case "MON":
		fallthrough
	case "THU":
		fallthrough
	case "WED":
		fallthrough
	case "FRI":
		*e = GetScheduleByIDScheduleTimetable2DaysOfWeekEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetScheduleByIDScheduleTimetable2DaysOfWeekEnum: %v", v)
	}
}

// GetScheduleByIDScheduleTimetable2MonthsEnum - Month, in three letters format.
type GetScheduleByIDScheduleTimetable2MonthsEnum string

const (
	GetScheduleByIDScheduleTimetable2MonthsEnumMar GetScheduleByIDScheduleTimetable2MonthsEnum = "MAR"
	GetScheduleByIDScheduleTimetable2MonthsEnumNov GetScheduleByIDScheduleTimetable2MonthsEnum = "NOV"
	GetScheduleByIDScheduleTimetable2MonthsEnumDec GetScheduleByIDScheduleTimetable2MonthsEnum = "DEC"
	GetScheduleByIDScheduleTimetable2MonthsEnumJun GetScheduleByIDScheduleTimetable2MonthsEnum = "JUN"
	GetScheduleByIDScheduleTimetable2MonthsEnumMay GetScheduleByIDScheduleTimetable2MonthsEnum = "MAY"
	GetScheduleByIDScheduleTimetable2MonthsEnumOct GetScheduleByIDScheduleTimetable2MonthsEnum = "OCT"
	GetScheduleByIDScheduleTimetable2MonthsEnumFeb GetScheduleByIDScheduleTimetable2MonthsEnum = "FEB"
	GetScheduleByIDScheduleTimetable2MonthsEnumApr GetScheduleByIDScheduleTimetable2MonthsEnum = "APR"
	GetScheduleByIDScheduleTimetable2MonthsEnumSep GetScheduleByIDScheduleTimetable2MonthsEnum = "SEP"
	GetScheduleByIDScheduleTimetable2MonthsEnumAug GetScheduleByIDScheduleTimetable2MonthsEnum = "AUG"
	GetScheduleByIDScheduleTimetable2MonthsEnumJan GetScheduleByIDScheduleTimetable2MonthsEnum = "JAN"
	GetScheduleByIDScheduleTimetable2MonthsEnumJul GetScheduleByIDScheduleTimetable2MonthsEnum = "JUL"
)

func (e GetScheduleByIDScheduleTimetable2MonthsEnum) ToPointer() *GetScheduleByIDScheduleTimetable2MonthsEnum {
	return &e
}

func (e *GetScheduleByIDScheduleTimetable2MonthsEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MAR":
		fallthrough
	case "NOV":
		fallthrough
	case "DEC":
		fallthrough
	case "JUN":
		fallthrough
	case "MAY":
		fallthrough
	case "OCT":
		fallthrough
	case "FEB":
		fallthrough
	case "APR":
		fallthrough
	case "SEP":
		fallthrough
	case "AUG":
		fallthrough
	case "JAN":
		fallthrough
	case "JUL":
		*e = GetScheduleByIDScheduleTimetable2MonthsEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetScheduleByIDScheduleTimetable2MonthsEnum: %v", v)
	}
}

// GetScheduleByIDScheduleTimetable2 - Timetable that specifies when a schedule triggers.
type GetScheduleByIDScheduleTimetable2 struct {
	// Days in a month in which the schedule triggers. This is mutually exclusive with days in a week.
	DaysOfMonth []int64 `json:"days-of-month"`
	// Days in a week in which the schedule triggers.
	DaysOfWeek []GetScheduleByIDScheduleTimetable2DaysOfWeekEnum `json:"days-of-week,omitempty"`
	// Hours in a day in which the schedule triggers.
	HoursOfDay []int64 `json:"hours-of-day"`
	// Months in which the schedule triggers.
	Months []GetScheduleByIDScheduleTimetable2MonthsEnum `json:"months,omitempty"`
	// Number of times a schedule triggers per hour, value must be between 1 and 60
	PerHour int64 `json:"per-hour"`
}

// GetScheduleByIDScheduleTimetable1DaysOfWeekEnum - Day in a week, in three letters format
type GetScheduleByIDScheduleTimetable1DaysOfWeekEnum string

const (
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumTue GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "TUE"
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumSat GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "SAT"
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumSun GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "SUN"
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumMon GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "MON"
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumThu GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "THU"
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumWed GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "WED"
	GetScheduleByIDScheduleTimetable1DaysOfWeekEnumFri GetScheduleByIDScheduleTimetable1DaysOfWeekEnum = "FRI"
)

func (e GetScheduleByIDScheduleTimetable1DaysOfWeekEnum) ToPointer() *GetScheduleByIDScheduleTimetable1DaysOfWeekEnum {
	return &e
}

func (e *GetScheduleByIDScheduleTimetable1DaysOfWeekEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TUE":
		fallthrough
	case "SAT":
		fallthrough
	case "SUN":
		fallthrough
	case "MON":
		fallthrough
	case "THU":
		fallthrough
	case "WED":
		fallthrough
	case "FRI":
		*e = GetScheduleByIDScheduleTimetable1DaysOfWeekEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetScheduleByIDScheduleTimetable1DaysOfWeekEnum: %v", v)
	}
}

// GetScheduleByIDScheduleTimetable1MonthsEnum - Month, in three letters format.
type GetScheduleByIDScheduleTimetable1MonthsEnum string

const (
	GetScheduleByIDScheduleTimetable1MonthsEnumMar GetScheduleByIDScheduleTimetable1MonthsEnum = "MAR"
	GetScheduleByIDScheduleTimetable1MonthsEnumNov GetScheduleByIDScheduleTimetable1MonthsEnum = "NOV"
	GetScheduleByIDScheduleTimetable1MonthsEnumDec GetScheduleByIDScheduleTimetable1MonthsEnum = "DEC"
	GetScheduleByIDScheduleTimetable1MonthsEnumJun GetScheduleByIDScheduleTimetable1MonthsEnum = "JUN"
	GetScheduleByIDScheduleTimetable1MonthsEnumMay GetScheduleByIDScheduleTimetable1MonthsEnum = "MAY"
	GetScheduleByIDScheduleTimetable1MonthsEnumOct GetScheduleByIDScheduleTimetable1MonthsEnum = "OCT"
	GetScheduleByIDScheduleTimetable1MonthsEnumFeb GetScheduleByIDScheduleTimetable1MonthsEnum = "FEB"
	GetScheduleByIDScheduleTimetable1MonthsEnumApr GetScheduleByIDScheduleTimetable1MonthsEnum = "APR"
	GetScheduleByIDScheduleTimetable1MonthsEnumSep GetScheduleByIDScheduleTimetable1MonthsEnum = "SEP"
	GetScheduleByIDScheduleTimetable1MonthsEnumAug GetScheduleByIDScheduleTimetable1MonthsEnum = "AUG"
	GetScheduleByIDScheduleTimetable1MonthsEnumJan GetScheduleByIDScheduleTimetable1MonthsEnum = "JAN"
	GetScheduleByIDScheduleTimetable1MonthsEnumJul GetScheduleByIDScheduleTimetable1MonthsEnum = "JUL"
)

func (e GetScheduleByIDScheduleTimetable1MonthsEnum) ToPointer() *GetScheduleByIDScheduleTimetable1MonthsEnum {
	return &e
}

func (e *GetScheduleByIDScheduleTimetable1MonthsEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MAR":
		fallthrough
	case "NOV":
		fallthrough
	case "DEC":
		fallthrough
	case "JUN":
		fallthrough
	case "MAY":
		fallthrough
	case "OCT":
		fallthrough
	case "FEB":
		fallthrough
	case "APR":
		fallthrough
	case "SEP":
		fallthrough
	case "AUG":
		fallthrough
	case "JAN":
		fallthrough
	case "JUL":
		*e = GetScheduleByIDScheduleTimetable1MonthsEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetScheduleByIDScheduleTimetable1MonthsEnum: %v", v)
	}
}

// GetScheduleByIDScheduleTimetable1 - Timetable that specifies when a schedule triggers.
type GetScheduleByIDScheduleTimetable1 struct {
	// Days in a month in which the schedule triggers. This is mutually exclusive with days in a week.
	DaysOfMonth []int64 `json:"days-of-month,omitempty"`
	// Days in a week in which the schedule triggers.
	DaysOfWeek []GetScheduleByIDScheduleTimetable1DaysOfWeekEnum `json:"days-of-week"`
	// Hours in a day in which the schedule triggers.
	HoursOfDay []int64 `json:"hours-of-day"`
	// Months in which the schedule triggers.
	Months []GetScheduleByIDScheduleTimetable1MonthsEnum `json:"months,omitempty"`
	// Number of times a schedule triggers per hour, value must be between 1 and 60
	PerHour int64 `json:"per-hour"`
}

// GetScheduleByIDSchedule - A schedule response
type GetScheduleByIDSchedule struct {
	// The attribution actor who will run the scheduled pipeline.
	Actor GetScheduleByIDScheduleUser `json:"actor"`
	// The date and time the pipeline was created.
	CreatedAt time.Time `json:"created-at"`
	// Description of the schedule.
	Description string `json:"description"`
	// The unique ID of the schedule.
	ID string `json:"id"`
	// Name of the schedule.
	Name string `json:"name"`
	// Pipeline parameters represented as key-value pairs. Must contain branch or tag.
	Parameters map[string]interface{} `json:"parameters"`
	// The project-slug for the schedule
	ProjectSlug string `json:"project-slug"`
	// Timetable that specifies when a schedule triggers.
	Timetable interface{} `json:"timetable"`
	// The date and time the pipeline was last updated.
	UpdatedAt time.Time `json:"updated-at"`
}

type GetScheduleByIDResponse struct {
	ContentType string
	// A schedule object.
	Schedule    *GetScheduleByIDSchedule
	StatusCode  int
	RawResponse *http.Response
	// Error response.
	GetScheduleByIDDefaultApplicationJSONObject *GetScheduleByIDDefaultApplicationJSON
}
