// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetTestsRequest struct {
	// The number of the job.
	JobNumber interface{} `pathParam:"style=simple,explode=false,name=job-number"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// GetTestsDefaultApplicationJSON - Error response.
type GetTestsDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type GetTestsTestsResponseItems struct {
	// The programmatic location of the test.
	Classname string `json:"classname"`
	// The file in which the test is defined.
	File string `json:"file"`
	// The failure message associated with the test.
	Message string `json:"message"`
	// The name of the test.
	Name string `json:"name"`
	// Indication of whether the test succeeded.
	Result string `json:"result"`
	// The time it took to run the test in seconds
	RunTime float64 `json:"run_time"`
	// The program that generated the test results
	Source string `json:"source"`
}

// GetTestsTestsResponse - A paginated list of test results.
type GetTestsTestsResponse struct {
	Items []GetTestsTestsResponseItems `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

type GetTestsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A paginated list of test results.
	TestsResponse *GetTestsTestsResponse
	// Error response.
	GetTestsDefaultApplicationJSONObject *GetTestsDefaultApplicationJSON
}
