// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type ListWorkflowJobsRequest struct {
	// The unique ID of the workflow.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

// ListWorkflowJobsDefaultApplicationJSON - Error response.
type ListWorkflowJobsDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListWorkflowJobsWorkflowJobListResponseJobStatusEnum - The current status of the job.
type ListWorkflowJobsWorkflowJobListResponseJobStatusEnum string

const (
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumSuccess            ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "success"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumRunning            ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "running"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumNotRun             ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "not_run"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumFailed             ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "failed"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumRetried            ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "retried"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumQueued             ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "queued"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumNotRunning         ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "not_running"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumInfrastructureFail ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "infrastructure_fail"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumTimedout           ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "timedout"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumOnHold             ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "on_hold"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumTerminatedUnknown  ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "terminated-unknown"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumBlocked            ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "blocked"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumCanceled           ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "canceled"
	ListWorkflowJobsWorkflowJobListResponseJobStatusEnumUnauthorized       ListWorkflowJobsWorkflowJobListResponseJobStatusEnum = "unauthorized"
)

func (e ListWorkflowJobsWorkflowJobListResponseJobStatusEnum) ToPointer() *ListWorkflowJobsWorkflowJobListResponseJobStatusEnum {
	return &e
}

func (e *ListWorkflowJobsWorkflowJobListResponseJobStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "success":
		fallthrough
	case "running":
		fallthrough
	case "not_run":
		fallthrough
	case "failed":
		fallthrough
	case "retried":
		fallthrough
	case "queued":
		fallthrough
	case "not_running":
		fallthrough
	case "infrastructure_fail":
		fallthrough
	case "timedout":
		fallthrough
	case "on_hold":
		fallthrough
	case "terminated-unknown":
		fallthrough
	case "blocked":
		fallthrough
	case "canceled":
		fallthrough
	case "unauthorized":
		*e = ListWorkflowJobsWorkflowJobListResponseJobStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ListWorkflowJobsWorkflowJobListResponseJobStatusEnum: %s", s)
	}
}

// ListWorkflowJobsWorkflowJobListResponseJobTypeEnum - The type of job.
type ListWorkflowJobsWorkflowJobListResponseJobTypeEnum string

const (
	ListWorkflowJobsWorkflowJobListResponseJobTypeEnumBuild    ListWorkflowJobsWorkflowJobListResponseJobTypeEnum = "build"
	ListWorkflowJobsWorkflowJobListResponseJobTypeEnumApproval ListWorkflowJobsWorkflowJobListResponseJobTypeEnum = "approval"
)

func (e ListWorkflowJobsWorkflowJobListResponseJobTypeEnum) ToPointer() *ListWorkflowJobsWorkflowJobListResponseJobTypeEnum {
	return &e
}

func (e *ListWorkflowJobsWorkflowJobListResponseJobTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "build":
		fallthrough
	case "approval":
		*e = ListWorkflowJobsWorkflowJobListResponseJobTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ListWorkflowJobsWorkflowJobListResponseJobTypeEnum: %s", s)
	}
}

// ListWorkflowJobsWorkflowJobListResponseJob - Job
type ListWorkflowJobsWorkflowJobListResponseJob struct {
	// The unique ID of the job.
	ApprovalRequestID *string `json:"approval_request_id,omitempty"`
	// The unique ID of the user.
	ApprovedBy *string `json:"approved_by,omitempty"`
	// The unique ID of the user.
	CanceledBy *string `json:"canceled_by,omitempty"`
	// A sequence of the unique job IDs for the jobs that this job depends upon in the workflow.
	Dependencies []string `json:"dependencies"`
	// The unique ID of the job.
	ID string `json:"id"`
	// The number of the job.
	JobNumber *int64 `json:"job_number,omitempty"`
	// The name of the job.
	Name string `json:"name"`
	// The project-slug for the job.
	ProjectSlug string `json:"project_slug"`
	// The date and time the job started.
	StartedAt time.Time `json:"started_at"`
	// The current status of the job.
	Status ListWorkflowJobsWorkflowJobListResponseJobStatusEnum `json:"status"`
	// The time when the job stopped.
	StoppedAt *time.Time `json:"stopped_at,omitempty"`
	// The type of job.
	Type ListWorkflowJobsWorkflowJobListResponseJobTypeEnum `json:"type"`
}

// ListWorkflowJobsWorkflowJobListResponse - A paginated sequence of jobs.
type ListWorkflowJobsWorkflowJobListResponse struct {
	Items []ListWorkflowJobsWorkflowJobListResponseJob `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

type ListWorkflowJobsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A paginated sequence of jobs.
	WorkflowJobListResponse *ListWorkflowJobsWorkflowJobListResponse
	// Error response.
	ListWorkflowJobsDefaultApplicationJSONObject *ListWorkflowJobsDefaultApplicationJSON
}
