// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"time"
)

type ListEnvironmentVariablesFromContextRequest struct {
	// ID of the context (UUID)
	ContextID string `pathParam:"style=simple,explode=false,name=context-id"`
	// A token to retrieve the next page of results.
	PageToken *string `queryParam:"style=form,explode=true,name=page-token"`
}

// ListEnvironmentVariablesFromContextDefaultApplicationJSON - Error response.
type ListEnvironmentVariablesFromContextDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListEnvironmentVariablesFromContext200ApplicationJSONItems struct {
	// ID of the context (UUID)
	ContextID string `json:"context_id"`
	// The date and time the environment variable was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the environment variable was updated
	UpdatedAt time.Time `json:"updated_at"`
	// The name of the environment variable
	Variable string `json:"variable"`
}

// ListEnvironmentVariablesFromContext200ApplicationJSON - A paginated list of environment variables
type ListEnvironmentVariablesFromContext200ApplicationJSON struct {
	Items []ListEnvironmentVariablesFromContext200ApplicationJSONItems `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

type ListEnvironmentVariablesFromContextResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A paginated list of environment variables
	ListEnvironmentVariablesFromContext200ApplicationJSONObject *ListEnvironmentVariablesFromContext200ApplicationJSON
	// Error response.
	ListEnvironmentVariablesFromContextDefaultApplicationJSONObject *ListEnvironmentVariablesFromContextDefaultApplicationJSON
}
