// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListEnvVarsRequest struct {
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	ProjectSlug string `pathParam:"style=simple,explode=false,name=project-slug"`
}

// ListEnvVarsDefaultApplicationJSON - Error response.
type ListEnvVarsDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListEnvVarsEnvironmentVariableListResponseEnvironmentVariablePair struct {
	// The name of the environment variable.
	Name string `json:"name"`
	// The value of the environment variable.
	Value string `json:"value"`
}

// ListEnvVarsEnvironmentVariableListResponse - A sequence of environment variables.
type ListEnvVarsEnvironmentVariableListResponse struct {
	Items []ListEnvVarsEnvironmentVariableListResponseEnvironmentVariablePair `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

type ListEnvVarsResponse struct {
	ContentType string
	// A sequence of environment variables.
	EnvironmentVariableListResponse *ListEnvVarsEnvironmentVariableListResponse
	StatusCode                      int
	RawResponse                     *http.Response
	// Error response.
	ListEnvVarsDefaultApplicationJSONObject *ListEnvVarsDefaultApplicationJSON
}
