// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type ListPipelinesRequest struct {
	// Only include entries created by your user.
	Mine *bool `queryParam:"style=form,explode=true,name=mine"`
	// Org slug in the form `vcs-slug/org-name`
	OrgSlug *string `queryParam:"style=form,explode=true,name=org-slug"`
	// A token to retrieve the next page of results.
	PageToken *string `queryParam:"style=form,explode=true,name=page-token"`
}

// ListPipelinesDefaultApplicationJSON - Error response.
type ListPipelinesDefaultApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListPipelinesPipelineListResponsePipelineErrorsTypeEnum - The type of error.
type ListPipelinesPipelineListResponsePipelineErrorsTypeEnum string

const (
	ListPipelinesPipelineListResponsePipelineErrorsTypeEnumConfig      ListPipelinesPipelineListResponsePipelineErrorsTypeEnum = "config"
	ListPipelinesPipelineListResponsePipelineErrorsTypeEnumConfigFetch ListPipelinesPipelineListResponsePipelineErrorsTypeEnum = "config-fetch"
	ListPipelinesPipelineListResponsePipelineErrorsTypeEnumTimeout     ListPipelinesPipelineListResponsePipelineErrorsTypeEnum = "timeout"
	ListPipelinesPipelineListResponsePipelineErrorsTypeEnumPermission  ListPipelinesPipelineListResponsePipelineErrorsTypeEnum = "permission"
	ListPipelinesPipelineListResponsePipelineErrorsTypeEnumOther       ListPipelinesPipelineListResponsePipelineErrorsTypeEnum = "other"
	ListPipelinesPipelineListResponsePipelineErrorsTypeEnumPlan        ListPipelinesPipelineListResponsePipelineErrorsTypeEnum = "plan"
)

func (e ListPipelinesPipelineListResponsePipelineErrorsTypeEnum) ToPointer() *ListPipelinesPipelineListResponsePipelineErrorsTypeEnum {
	return &e
}

func (e *ListPipelinesPipelineListResponsePipelineErrorsTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "config":
		fallthrough
	case "config-fetch":
		fallthrough
	case "timeout":
		fallthrough
	case "permission":
		fallthrough
	case "other":
		fallthrough
	case "plan":
		*e = ListPipelinesPipelineListResponsePipelineErrorsTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPipelinesPipelineListResponsePipelineErrorsTypeEnum: %v", v)
	}
}

// ListPipelinesPipelineListResponsePipelineErrors - An error with a type and message.
type ListPipelinesPipelineListResponsePipelineErrors struct {
	// A human-readable error message.
	Message string `json:"message"`
	// The type of error.
	Type ListPipelinesPipelineListResponsePipelineErrorsTypeEnum `json:"type"`
}

// ListPipelinesPipelineListResponsePipelineStateEnum - The current state of the pipeline.
type ListPipelinesPipelineListResponsePipelineStateEnum string

const (
	ListPipelinesPipelineListResponsePipelineStateEnumCreated      ListPipelinesPipelineListResponsePipelineStateEnum = "created"
	ListPipelinesPipelineListResponsePipelineStateEnumErrored      ListPipelinesPipelineListResponsePipelineStateEnum = "errored"
	ListPipelinesPipelineListResponsePipelineStateEnumSetupPending ListPipelinesPipelineListResponsePipelineStateEnum = "setup-pending"
	ListPipelinesPipelineListResponsePipelineStateEnumSetup        ListPipelinesPipelineListResponsePipelineStateEnum = "setup"
	ListPipelinesPipelineListResponsePipelineStateEnumPending      ListPipelinesPipelineListResponsePipelineStateEnum = "pending"
)

func (e ListPipelinesPipelineListResponsePipelineStateEnum) ToPointer() *ListPipelinesPipelineListResponsePipelineStateEnum {
	return &e
}

func (e *ListPipelinesPipelineListResponsePipelineStateEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created":
		fallthrough
	case "errored":
		fallthrough
	case "setup-pending":
		fallthrough
	case "setup":
		fallthrough
	case "pending":
		*e = ListPipelinesPipelineListResponsePipelineStateEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPipelinesPipelineListResponsePipelineStateEnum: %v", v)
	}
}

// ListPipelinesPipelineListResponsePipelineTriggerActor - The user who triggered the Pipeline.
type ListPipelinesPipelineListResponsePipelineTriggerActor struct {
	// URL to the user's avatar on the VCS
	AvatarURL string `json:"avatar_url"`
	// The login information for the user on the VCS.
	Login string `json:"login"`
}

// ListPipelinesPipelineListResponsePipelineTriggerTypeEnum - The type of trigger.
type ListPipelinesPipelineListResponsePipelineTriggerTypeEnum string

const (
	ListPipelinesPipelineListResponsePipelineTriggerTypeEnumScheduledPipeline ListPipelinesPipelineListResponsePipelineTriggerTypeEnum = "scheduled_pipeline"
	ListPipelinesPipelineListResponsePipelineTriggerTypeEnumExplicit          ListPipelinesPipelineListResponsePipelineTriggerTypeEnum = "explicit"
	ListPipelinesPipelineListResponsePipelineTriggerTypeEnumAPI               ListPipelinesPipelineListResponsePipelineTriggerTypeEnum = "api"
	ListPipelinesPipelineListResponsePipelineTriggerTypeEnumWebhook           ListPipelinesPipelineListResponsePipelineTriggerTypeEnum = "webhook"
)

func (e ListPipelinesPipelineListResponsePipelineTriggerTypeEnum) ToPointer() *ListPipelinesPipelineListResponsePipelineTriggerTypeEnum {
	return &e
}

func (e *ListPipelinesPipelineListResponsePipelineTriggerTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "scheduled_pipeline":
		fallthrough
	case "explicit":
		fallthrough
	case "api":
		fallthrough
	case "webhook":
		*e = ListPipelinesPipelineListResponsePipelineTriggerTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPipelinesPipelineListResponsePipelineTriggerTypeEnum: %v", v)
	}
}

// ListPipelinesPipelineListResponsePipelineTrigger - A summary of the trigger.
type ListPipelinesPipelineListResponsePipelineTrigger struct {
	// The user who triggered the Pipeline.
	Actor ListPipelinesPipelineListResponsePipelineTriggerActor `json:"actor"`
	// The date and time the trigger was received.
	ReceivedAt time.Time `json:"received_at"`
	// The type of trigger.
	Type ListPipelinesPipelineListResponsePipelineTriggerTypeEnum `json:"type"`
}

// ListPipelinesPipelineListResponsePipelineVcsCommit - The latest commit in the pipeline.
type ListPipelinesPipelineListResponsePipelineVcsCommit struct {
	// The body of the commit message.
	Body string `json:"body"`
	// The subject of the commit message.
	Subject string `json:"subject"`
}

// ListPipelinesPipelineListResponsePipelineVcs - VCS information for the pipeline.
type ListPipelinesPipelineListResponsePipelineVcs struct {
	// The branch where the pipeline ran. The HEAD commit on this branch was used for the pipeline. Note that `branch` and `tag` are mutually exclusive. To trigger a pipeline for a PR by number use `pull/<number>/head` for the PR ref or `pull/<number>/merge` for the merge ref (GitHub only).
	Branch *string `json:"branch,omitempty"`
	// The latest commit in the pipeline.
	Commit *ListPipelinesPipelineListResponsePipelineVcsCommit `json:"commit,omitempty"`
	// URL for the repository where the trigger originated. For fork-PR pipelines, this is the URL to the fork. For other pipelines the `origin_` and `target_repository_url`s will be the same.
	OriginRepositoryURL string `json:"origin_repository_url"`
	// Name of the VCS provider (e.g. GitHub, Bitbucket).
	ProviderName string `json:"provider_name"`
	// The code review id.
	ReviewID *string `json:"review_id,omitempty"`
	// The code review URL.
	ReviewURL *string `json:"review_url,omitempty"`
	// The code revision the pipeline ran.
	Revision string `json:"revision"`
	// The tag used by the pipeline. The commit that this tag points to was used for the pipeline. Note that `branch` and `tag` are mutually exclusive.
	Tag *string `json:"tag,omitempty"`
	// URL for the repository the trigger targets (i.e. the repository where the PR will be merged). For fork-PR pipelines, this is the URL to the parent repo. For other pipelines, the `origin_` and `target_repository_url`s will be the same.
	TargetRepositoryURL string `json:"target_repository_url"`
}

// ListPipelinesPipelineListResponsePipeline - A pipeline response.
type ListPipelinesPipelineListResponsePipeline struct {
	// The date and time the pipeline was created.
	CreatedAt time.Time `json:"created_at"`
	// A sequence of errors that have occurred within the pipeline.
	Errors []ListPipelinesPipelineListResponsePipelineErrors `json:"errors"`
	// The unique ID of the pipeline.
	ID string `json:"id"`
	// The number of the pipeline.
	Number int64 `json:"number"`
	// The project-slug for the pipeline.
	ProjectSlug string `json:"project_slug"`
	// The current state of the pipeline.
	State ListPipelinesPipelineListResponsePipelineStateEnum `json:"state"`
	// A summary of the trigger.
	Trigger           ListPipelinesPipelineListResponsePipelineTrigger `json:"trigger"`
	TriggerParameters map[string]interface{}                           `json:"trigger_parameters,omitempty"`
	// The date and time the pipeline was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// VCS information for the pipeline.
	Vcs *ListPipelinesPipelineListResponsePipelineVcs `json:"vcs,omitempty"`
}

// ListPipelinesPipelineListResponse - List of pipelines
type ListPipelinesPipelineListResponse struct {
	Items []ListPipelinesPipelineListResponsePipeline `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

type ListPipelinesResponse struct {
	ContentType string
	// A sequence of pipelines.
	PipelineListResponse *ListPipelinesPipelineListResponse
	StatusCode           int
	RawResponse          *http.Response
	// Error response.
	ListPipelinesDefaultApplicationJSONObject *ListPipelinesDefaultApplicationJSON
}
