// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SchemeBasicAuth struct {
	Password string `security:"name=password"`
	Username string `security:"name=username"`
}

type Security struct {
	APIKeyHeader *string          `security:"scheme,type=apiKey,subtype=header,name=Circle-Token"`
	APIKeyQuery  *string          `security:"scheme,type=apiKey,subtype=query,name=circle-token"`
	BasicAuth    *SchemeBasicAuth `security:"scheme,type=http,subtype=basic"`
}
